name: Auto Commit

on:
  schedule:
    - cron: '5 15 * * *'
    - cron: '5 15 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make a commit
        run: |
          date > date.txt
          git config --global user.email "prakharsinha3125@gmail.com"
          git config --global user.name "prakhar3125"
          git add date.txt
          git commit -m "Automated commit"
          git push
