name: Auto Commit

on:
  schedule:
    - cron: '5 10 * * *'  # 10:05 AM UTC, which is 3:35 PM IST

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make a commit
        run: |
          date > date.txt
          git config --global user.email "prakharsinha3125@gmail.com"
          git config --global user.name "prakhar3125"
          git add date.txt
          git commit -m "Automated commit"
          git push
